on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    #ok
    steps: 
      - uses: actions/checkout@v4
        with:
          repository: cupglassDEV/rpi-nix
          ref: 'master'
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: denoland/setup-deno@v1.5.1
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Building
        run: git pull
      - name: Install needed deps
        run: sudo apt-get install zstd
      - name: Start building
        run: |
          cd dist
          mkdir ${{ inputs.version }}
          cd ${{ inputs.version }}
          find ../../ -type f -name "*.nix" -execdir rsync {} "$HOME"/dist/${{inputd.version}} \;
          
          nix build .#packages.aarch64-linux.sdcard
          nix flake check
          deno run ../../build/moveFlakeResult.js ${{ inputs.version }}-desktop
          
          nix build .#packages.aarch64-linux-remoteable.sdcard
          nix flake check
          deno run ../../build/moveFlakeResult.js ${{ inputs.version }}-desktop-remoteable
          
          find ./ -type f -name "*.nix" -execdir rm -f {} \;
          find ./ -type f -name "*.lock" -execdir rm -f {} \;
          
          find ./ -type f -name "*.img" -execdir zstd {} \;
          find ./ -type f -name "*.img" -execdir rm -f {} \;
          
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "Build image for version ${{ inputs.version }}"
          git push
