name: Cupglassdev Nix Builder
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    #ok
    steps: 
      - uses: actions/checkout@v4
        with:
          repository: cupglassDEV/rpi-nix
          ref: 'master'
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            extra-platforms = aarch64-linux i686-linux
      - uses: denoland/setup-deno@v1.5.1
      - name: (NUKE) delete temp
        run: export TMPDIR=/tmp; export SHIT="$PWD"; cd /tmp; sudo rm -rf *; cd ..
      - name: (NUKE v2) delete soo many temps that idk what is this
        run: sudo rm -rf /usr/share/dotnet; sudo rm -rf /opt/ghc; sudo rm -rf "/usr/local/share/boost"; sudo rm -rf "$AGENT_TOOLSDIRECTORY"; cd "$SHIT"
      - uses: jlumbroso/free-disk-space@main
      - name: Pull everything no matter what
        run: git pull
      - name: Install needed deps
        run: sudo apt-get install zstd
      - name: Run mkVersionDir.js from ./build folder (Make version folder from ./dist)
        run: deno run -A ./build/mkVersionDir.js ${{ inputs.version }}
        # fuck deprecation, embrace the os itself
      - name: Build the image itself
        run: nix build '.#nixosConfigurations.rpi-nix.config.system.build.sdImage' --extra-experimental-features nix-command --extra-experimental-features flakes
      - name: Run moveFlakeResult.js from ./build folder (Get the 'result' symlink file, then move it to version folder inside ./dist)
        run: deno run -A ./build/moveFlakeResult.js ${{ inputs.version }} desktop
      - name: Run compressVersion.js from ./build folder (Compress disk image to Facebook Zstandart)
        run: deno run -A ./build/compressVersion.js ${{ inputs.version }}
      - name: Commit
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "Build image for version ${{ inputs.version }}"
          git push
