name: Cupglassdev Nix Builder
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    #ok
    steps: 
      - uses: actions/checkout@v4
        with:
          repository: cupglassDEV/rpi-nix
          ref: 'master'
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: denoland/setup-deno@v1.5.1
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Building
        run: git pull
      - name: Install needed deps
        run: sudo apt-get install zstd
      - name: Export 
        run: deno run ./build/exportThis.js
      - name: Refresh bash
        run: source ~/.bash_rc
      - name: Run mkVersionDir.js from ./build folder (Make version folder from ./dist)
        run: run mkVersionDir ${{ inputs.version }}
      - name: Build aarch64-linux
        run: |
          nix build .#packages.aarch64-linux.sdcard
          nix flake check
      - name: (Wave 1) Run moveFlakeResult.js from ./build folder (Get the 'result' symlink file, then move it to version folder inside ./dist)
        run: run moveFlakeResult ${{ inputs.version }} desktop
      - name: Build aarch64-linux.remoteable (VNC + SSH)
        run: |
          nix build .#packages.aarch64-linux-remoteable.sdcard
          nix flake check
      - name: (Wave 2) Run moveFlakeResult.js from ./build folder (Get the 'result' symlink file, then move it to version folder inside ./dist)
        run: run moveFlakeResult ${{ inputs.version }} desktop-remoteable
      - name: Run compressVersion.js from ./build folder (Compress disk image to Facebook Zstandart)
        run: run compressVersion
      - name: Commit
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "Build image for version ${{ inputs.version }}"
          git push
