name: Cupglassdev TestSuite
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Make a fake img file
        run: touch nixagain-${{ inputs.version }}.img
      - name: Make a symlink from the file
        run: ln -s nixagain.img result
      - name: Run moveFlakeResult.js from ./build folder (Get the 'result' symlink file, then move it to version folder inside ./dist)
        run: deno run -A ./build/moveFlakeResult.js ${{ inputs.version }} desktop
      - name: Run compressVersion.js from ./build folder (Compress disk image to Facebook Zstandart)
        run: deno run -A ./build/compressVersion.js ${{ inputs.version }}
      - name: Ls'ed main repo
        run: ls
      - name: Ls'ed the distribution folder
        run: ls dist
      - name: Ls'ed the version folder
        run: ls dist/${{ inputs.version }}
